export const flightsData = [
  {
    id: '1',
    airline: 'Turkish Airlines',
    logo: 'TK', 
    from: 'IST',
    to: 'NYC',
    date: '2024-05-20',
    time: '14:30',
    duration: '10h 20m',
    price: 850,
    currency: '$',
  },
  {
    id: '2',
    airline: 'Pegasus',
    logo: 'PC',
    from: 'IST',
    to: 'LHR',
    date: '2024-05-21',
    time: '09:15',
    duration: '4h 10m',
    price: 120,
    currency: '$',
  },
  {
    id: '3',
    airline: 'Lufthansa',
    logo: 'LH',
    from: 'IST',
    to: 'BER',
    date: '2024-05-22',
    time: '18:45',
    duration: '3h 05m',
    price: 200,
    currency: '$',
  },
  {
    id: '4',
    airline: 'Emirates',
    logo: 'EK',
    from: 'IST',
    to: 'DXB',
    date: '2024-05-23',
    time: '20:00',
    duration: '4h 30m',
    price: 450,
    currency: '$',
  },
];